[pytest]
filterwarnings =
    ignore:websockets\.WebSocketClientProtocol is deprecated:DeprecationWarning:binance\.ws\.websocket_api
    ignore:websockets\.legacy is deprecated.*:DeprecationWarning:websockets\.legacy
